apiVersion: v1
kind: Service
metadata:
  name: simple-service
  labels:
    app: simple-service
spec:
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: simple-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service
spec:
  selector:
    matchLabels:
      app: simple-service
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
        - name: simple-service
          image: australia-southeast1-docker.pkg.dev/solo-test-236622/apac/simple-service:v0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "--port"
            - "9080"
          ports:
            - containerPort: 9080
          env:
            - name: LOG_LEVEL
              value: debug
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name